// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SchoolMedical.BusinessObject.Shared.Models.LocBP.Models;

public partial class MedicalReportsLocBp
{
    public int FkStudentProfileLocBpid { get; set; }

    public int MedicalReportsLocBpid { get; set; }

    public DateTime IncidentDate { get; set; }

    public string Location { get; set; }

    public string Description { get; set; }

    public string ActionTaken { get; set; }

    public DateTime ReportedDate { get; set; }

    public string WitnessName { get; set; }

    public bool ParentNotified { get; set; }

    public DateTime? ResolutionDate { get; set; }

    public bool Status { get; set; }

    public int SeverityLevel { get; set; }

/*
    public virtual StudentProfileLocBp FkStudentProfileLocBp { get; set; }*/
}