// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SchoolMedical.BusinessObject.Shared.Models.LocBP.Models;

public partial class StudentProfileLocBp
{
    public int StudentProfileLocBpid { get; set; }

    public string ParentName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime DateOfBirth { get; set; }

    public string Class { get; set; }

    public DateTime EnrollmentDate { get; set; }

    public string MedicalHistoryNote { get; set; }

    public string Address { get; set; }

    public bool Status { get; set; }
/*
    public virtual ICollection<MedicalReportsLocBp> MedicalReportsLocBps { get; set; } = new List<MedicalReportsLocBp>();*/
}